name: SAOStats
version: '${project.version}'
main: fr.soraxdubbing.saostats.SAOStats
api-version: 1.16
authors: [ SoraxDubbing ]
description: Plugin de modification d'items pour le serveur SAOFrance
depend: [NBTAPI]
commands:
  customise:
    description: Permet de customiser un item
    usage: /customise <item> <type> <value>
    aliases: [custom]
    permission: itemmodifiers.customise
    permission-message: "&cVous n'avez pas la permission d'utiliser cette commande"